name: VariableEnderChests
version: '${project.version}'
main: me.saif.betterenderchests.VariableEnderChests
author: minion325
api-version: '1.19'
folia-supported: true
softdepend:
  - PlaceholderAPI
  - ShowItem
  - InteractiveChat

dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
      join-classpath: true

libraries:
  - org.mariadb.jdbc:mariadb-java-client:3.5.7
